### ISSUE TITLE
Trouble understanding limitations

### ISSUE THREAD

**Issue by thallada** [correttojs/graphql-codegen-apollo-next-ssr#116]
This looks like the only way to use Apollo with TypeScript typed queries and Next.js SSR at the same time without a lot of boilerplate. However, I'm worried about the limitation listed in the README: "The limitation/advantage of this solution is that all the queries embedded into inner react components are ignored, unless covered by the top level cache.".

That sounds scary to me, I don't want queries to be ignored. What situations would I need to avoid to prevent that from happening? If I have all of my graphql queries as `graphql` files in the `src` folder like in the example will I be okay?

I also have a separate maybe unrelated question: if I wanted to make a client-side only graphql request, how would I do that with this library? Is that what `usePage` does?

**Comment by correttojs** [comment]
I added this note because the plugin doesn't offer the same functionality as [getDataFromTree](https://www.apollographql.com/docs/react/api/react/ssr/). The official apollo solution iterates over all the queries within the react tree, causing each time a new rendering. This plugins doesn't aim to run all the queries included in the react tree, but only the one explicitly defined in `getServerSideProps`. From the other end, this solution is simpler and more performant.

If you need a client-only request, you can use the react-apollo codegen plugin. I'd suggest you to take a look at the [typed-document-node](https://graphql-code-generator.com/docs/plugins/typed-document-node) which offers a simpler solution

**Comment by thallada** [comment]
Ok, so it only collects and runs queries that are in `getServerSideProps`. That makes more sense to me. I'll close this issue so I don't clutter your issues. Thanks for the making the library!

**Comment by correttojs** [comment]
You are welcome, I hope the explanation helped covering your use case
